package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Generic generated by hbm2java
 */
@Entity
@Table(name="generic"
    ,catalog="mr_database"
)
public class Generic  implements java.io.Serializable {


     private Integer genericId;
     private String genericName;
     private Set<Medicine> medicines = new HashSet<Medicine>(0);
     private Set<Offer> offers = new HashSet<Offer>(0);

    public Generic() {
    }

	
    public Generic(String genericName) {
        this.genericName = genericName;
    }
    public Generic(String genericName, Set<Medicine> medicines, Set<Offer> offers) {
       this.genericName = genericName;
       this.medicines = medicines;
       this.offers = offers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="generic_id", unique=true, nullable=false)
    public Integer getGenericId() {
        return this.genericId;
    }
    
    public void setGenericId(Integer genericId) {
        this.genericId = genericId;
    }

    
    @Column(name="generic_name", nullable=false, length=45)
    public String getGenericName() {
        return this.genericName;
    }
    
    public void setGenericName(String genericName) {
        this.genericName = genericName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="generic")
    public Set<Medicine> getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Set<Medicine> medicines) {
        this.medicines = medicines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="generic")
    public Set<Offer> getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set<Offer> offers) {
        this.offers = offers;
    }




}


