package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name="manager"
    ,catalog="mr_database"
)
public class Manager  implements java.io.Serializable {


     private Integer managerId;
     private Company company;
     private String managerName;
     private String managerAddress;
     private String managerMobile;
     private String managerEmail;
     private Set<MedicalRepresentative> medicalRepresentatives = new HashSet<MedicalRepresentative>(0);

    public Manager() {
    }

	
    public Manager(Company company, String managerName, String managerAddress, String managerMobile, String managerEmail) {
        this.company = company;
        this.managerName = managerName;
        this.managerAddress = managerAddress;
        this.managerMobile = managerMobile;
        this.managerEmail = managerEmail;
    }
    public Manager(Company company, String managerName, String managerAddress, String managerMobile, String managerEmail, Set<MedicalRepresentative> medicalRepresentatives) {
       this.company = company;
       this.managerName = managerName;
       this.managerAddress = managerAddress;
       this.managerMobile = managerMobile;
       this.managerEmail = managerEmail;
       this.medicalRepresentatives = medicalRepresentatives;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="manager_id", unique=true, nullable=false)
    public Integer getManagerId() {
        return this.managerId;
    }
    
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="company_id", nullable=false)
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

    
    @Column(name="manager_name", nullable=false, length=45)
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    
    @Column(name="manager_address", nullable=false, length=200)
    public String getManagerAddress() {
        return this.managerAddress;
    }
    
    public void setManagerAddress(String managerAddress) {
        this.managerAddress = managerAddress;
    }

    
    @Column(name="manager_mobile", nullable=false, length=45)
    public String getManagerMobile() {
        return this.managerMobile;
    }
    
    public void setManagerMobile(String managerMobile) {
        this.managerMobile = managerMobile;
    }

    
    @Column(name="manager_email", nullable=false, length=45)
    public String getManagerEmail() {
        return this.managerEmail;
    }
    
    public void setManagerEmail(String managerEmail) {
        this.managerEmail = managerEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="manager")
    public Set<MedicalRepresentative> getMedicalRepresentatives() {
        return this.medicalRepresentatives;
    }
    
    public void setMedicalRepresentatives(Set<MedicalRepresentative> medicalRepresentatives) {
        this.medicalRepresentatives = medicalRepresentatives;
    }




}


