package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeasurementUnit generated by hbm2java
 */
@Entity
@Table(name="measurement_unit"
    ,catalog="mr_database"
)
public class MeasurementUnit  implements java.io.Serializable {


     private Integer measurementId;
     private String measurementType;
     private Set<Medicine> medicines = new HashSet<Medicine>(0);

    public MeasurementUnit() {
    }

	
    public MeasurementUnit(String measurementType) {
        this.measurementType = measurementType;
    }
    public MeasurementUnit(String measurementType, Set<Medicine> medicines) {
       this.measurementType = measurementType;
       this.medicines = medicines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="measurement_id", unique=true, nullable=false)
    public Integer getMeasurementId() {
        return this.measurementId;
    }
    
    public void setMeasurementId(Integer measurementId) {
        this.measurementId = measurementId;
    }

    
    @Column(name="measurement_type", nullable=false, length=45)
    public String getMeasurementType() {
        return this.measurementType;
    }
    
    public void setMeasurementType(String measurementType) {
        this.measurementType = measurementType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="measurementUnit")
    public Set<Medicine> getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Set<Medicine> medicines) {
        this.medicines = medicines;
    }




}


