package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedicineType generated by hbm2java
 */
@Entity
@Table(name="medicine_type"
    ,catalog="mr_database"
)
public class MedicineType  implements java.io.Serializable {


     private Integer typeId;
     private String typeName;
     private Set<Medicine> medicines = new HashSet<Medicine>(0);
     private Set<Offer> offers = new HashSet<Offer>(0);

    public MedicineType() {
    }

	
    public MedicineType(String typeName) {
        this.typeName = typeName;
    }
    public MedicineType(String typeName, Set<Medicine> medicines, Set<Offer> offers) {
       this.typeName = typeName;
       this.medicines = medicines;
       this.offers = offers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="type_id", unique=true, nullable=false)
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    
    @Column(name="type_name", nullable=false, length=45)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicineType")
    public Set<Medicine> getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Set<Medicine> medicines) {
        this.medicines = medicines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicineType")
    public Set<Offer> getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set<Offer> offers) {
        this.offers = offers;
    }




}


