package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name="order_detail"
    ,catalog="mr_database"
)
public class OrderDetail  implements java.io.Serializable {


     private Integer odId;
     private Medicine medicine;
     private Order order;
     private float quantity;
     private double price;

    public OrderDetail() {
    }

    public OrderDetail(Medicine medicine, Order order, float quantity, double price) {
       this.medicine = medicine;
       this.order = order;
       this.quantity = quantity;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="od_id", unique=true, nullable=false)
    public Integer getOdId() {
        return this.odId;
    }
    
    public void setOdId(Integer odId) {
        this.odId = odId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="medicine_id", nullable=false)
    public Medicine getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

    
    @Column(name="quantity", nullable=false, precision=12, scale=0)
    public float getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(float quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


