package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShopUser generated by hbm2java
 */
@Entity
@Table(name="shop_user"
    ,catalog="mr_database"
)
public class ShopUser  implements java.io.Serializable {


     private Integer shopId;
     private MedicalRepresentative medicalRepresentative;
     private String shopName;
     private String proprietorName;
     private String shopAddress;
     private String shopMobile;
     private String shopPhone;
     private String shopEmail;

    public ShopUser() {
    }

    public ShopUser(MedicalRepresentative medicalRepresentative, String shopName, String proprietorName, String shopAddress, String shopMobile, String shopPhone, String shopEmail) {
       this.medicalRepresentative = medicalRepresentative;
       this.shopName = shopName;
       this.proprietorName = proprietorName;
       this.shopAddress = shopAddress;
       this.shopMobile = shopMobile;
       this.shopPhone = shopPhone;
       this.shopEmail = shopEmail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="shop_id", unique=true, nullable=false)
    public Integer getShopId() {
        return this.shopId;
    }
    
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mr_id", nullable=false)
    public MedicalRepresentative getMedicalRepresentative() {
        return this.medicalRepresentative;
    }
    
    public void setMedicalRepresentative(MedicalRepresentative medicalRepresentative) {
        this.medicalRepresentative = medicalRepresentative;
    }

    
    @Column(name="shop_name", nullable=false, length=45)
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    
    @Column(name="proprietor_name", nullable=false, length=45)
    public String getProprietorName() {
        return this.proprietorName;
    }
    
    public void setProprietorName(String proprietorName) {
        this.proprietorName = proprietorName;
    }

    
    @Column(name="shop_address", nullable=false, length=200)
    public String getShopAddress() {
        return this.shopAddress;
    }
    
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress;
    }

    
    @Column(name="shop_mobile", nullable=false, length=45)
    public String getShopMobile() {
        return this.shopMobile;
    }
    
    public void setShopMobile(String shopMobile) {
        this.shopMobile = shopMobile;
    }

    
    @Column(name="shop_phone", nullable=false, length=45)
    public String getShopPhone() {
        return this.shopPhone;
    }
    
    public void setShopPhone(String shopPhone) {
        this.shopPhone = shopPhone;
    }

    
    @Column(name="shop_email", nullable=false, length=45)
    public String getShopEmail() {
        return this.shopEmail;
    }
    
    public void setShopEmail(String shopEmail) {
        this.shopEmail = shopEmail;
    }




}


