package com.marmansys.entity;
// Generated Dec 10, 2016 3:49:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zone generated by hbm2java
 */
@Entity
@Table(name="zone"
    ,catalog="mr_database"
)
public class Zone  implements java.io.Serializable {


     private Integer zoneId;
     private MedicalRepresentative medicalRepresentative;
     private String zoneName;
     private Set<MedicalRepresentative> medicalRepresentatives = new HashSet<MedicalRepresentative>(0);

    public Zone() {
    }

	
    public Zone(MedicalRepresentative medicalRepresentative, String zoneName) {
        this.medicalRepresentative = medicalRepresentative;
        this.zoneName = zoneName;
    }
    public Zone(MedicalRepresentative medicalRepresentative, String zoneName, Set<MedicalRepresentative> medicalRepresentatives) {
       this.medicalRepresentative = medicalRepresentative;
       this.zoneName = zoneName;
       this.medicalRepresentatives = medicalRepresentatives;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="zone_id", unique=true, nullable=false)
    public Integer getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mr_id", nullable=false)
    public MedicalRepresentative getMedicalRepresentative() {
        return this.medicalRepresentative;
    }
    
    public void setMedicalRepresentative(MedicalRepresentative medicalRepresentative) {
        this.medicalRepresentative = medicalRepresentative;
    }

    
    @Column(name="zone_name", nullable=false, length=45)
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zone")
    public Set<MedicalRepresentative> getMedicalRepresentatives() {
        return this.medicalRepresentatives;
    }
    
    public void setMedicalRepresentatives(Set<MedicalRepresentative> medicalRepresentatives) {
        this.medicalRepresentatives = medicalRepresentatives;
    }




}


